### ISSUE TITLE
Replicate sample naming guidelines

### ISSUE THREAD

**Issue by jeremymsimon** [SimoneTiberi/distinct#1]
Hey Simone-
Giving this package a try now with our scTransform counts as we briefly discussed on Twitter. One thing I wanted to make sure of was whether the naming scheme of my replicates mattered at all. The documentation is not very clear on this. Currently, my samples are named things like "e14-WT9-2" or "p0-mutant1-1". Does that matter at all, or as long as it is paired correctly with my condition information in the `colData` table is there no important naming convention?

Thanks!

Jeremy

**Comment by SimoneTiberi** [comment]
Hi Jeremy @jeremymsimon 
it is as you said: the naming doesn't matter, but the sample names in colData(x)$name_sample have to be coherent (the same ones) w.r.t. rownames(design).

Thanks for your feedback, we'll try to make this clearer.

Let me know if there are further issues.

Have a good one,
Simone

**Comment by jeremymsimon** [comment]
Great, thanks!
