### ISSUE TITLE
Mat::init(): requested size is too large

### ISSUE THREAD

**Issue by jeremymsimon** [SimoneTiberi/distinct#3]
Just tried running the newest github version (v1.1.3) and am getting this error below:

```
res_e14_logct = distinct_test(x = e14.sce, name_assays_expression = "logcounts",name_cluster = "ident",design=design,name_sample = "orig.ident",P = 10^3, min_non_zero_cells = 20,n_cores=4)
2 groups of samples provided
Data loaded, starting differential testing
Error in { : task 1 failed - "Mat::init(): requested size is too large"
```

Note that I changed environments and this is from an instance on a Mac, running OS X 10.13.6.

Edited to add that the same is true for a fresh linux install, and true whether I use 4 cores or just 1. 

Also note that I do not get this error for the test dataset, that seems to complete just fine.

**Comment by SimoneTiberi** [comment]
Hi Jeremy,
mmm, I am not sure what is causing the problem; it might have to do with RcppArmadillo.

Can you check if you get the same error with v 1.0.2 (or analogously 1.1.2) ?
Those 2 are the versions currently on Bioc (and Bioc devel).

Would it be possible to get your data and the code you're running?

Thanks,
Simone

**Comment by jeremymsimon** [comment]
Will give that a try shortly. My `rds` file is ~200MB. Do you have a good way for me to share that with you?

**Comment by SimoneTiberi** [comment]
I'd suggest Google drive, otherwise dropbox?

**Comment by jeremymsimon** [comment]
I'll share it from my Google cloud bucket but need a gmail address for you. Can you share yours with me either here or by DM if you prefer?

**Comment by jeremymsimon** [comment]
Same error on the bioconductor version

**Comment by SimoneTiberi** [comment]
simone.tiberi88@gmail.com

thanks

P.s., the new edits marginally involved `distinct_test`: it makes sense the error appears on both versions.

**Comment by jeremymsimon** [comment]
Just shared object with you, please use `alevin-seurat.test1.latest_version_e14_RNA_sceObject.rds`

To run, I have done the following:

```
e14.sce = readRDS("alevin-seurat.test1.latest_version_e14_RNA_sceObject.rds")
x = as.matrix(unique(colData(e14.sce)$orig.ident))
x = cbind(x,c(rep("T485A",5),rep("WT",6)))
colnames(x) = c("sample_id","gt")
x = as.data.frame(x)
metadata(e14.sce)$experiment_info = x

set.seed(61217)

samples = e14.sce@metadata$experiment_info$sample_id
group = e14.sce@metadata$experiment_info$gt
design = model.matrix(~group)
rownames(design) = samples

res_e14_logct = distinct_test(x = e14.sce, name_assays_expression = "logcounts",name_cluster = "ident",design=design,name_sample = "orig.ident",P = 10^3, min_non_zero_cells = 20)

```

**Comment by SimoneTiberi** [comment]
Thanks Jeremy,
I will give it a try and see if I understand what's going wrong.

**Comment by SimoneTiberi** [comment]
I got it: you are using `P = 10^3`, but in the new version of `distict_test` I define several P's (that depend on the significance level: the more significant a p-value is, the more permutations are used).

So, just remove P when calling `distinct_test` (eventually, I suggest increasing/decreasing P_4 only, but keep P_1, P_2, P_3 and P_4 in a non-decreasing order).

Sorry for not spotting this from your code!

Apparently I forgot to put a condition checking that P_1 <= P_2 <= P_3 <= P_4.
I will add it in the next update.

Let me know if you get further troubles.
Simone
