### ISSUE TITLE
design matrix reference group

### ISSUE THREAD

**Issue by crazyhottommy** [SimoneTiberi/distinct#5]
Hi Simone,
I am using distinct for my single-cell RNAseq data.
I specified the factors in my design:

```
print(design)
Intercept) grouprefractory_CR_C4D1
P105_CD3-           1                       0
P107_CD3-           1                       1
P138_CD3-           1                       0
P140_CD3-           1                       1
```

but the logFC result chooses C4D1 as a reference group.

```
log2FC_refractory_CR_C1D1/refractory_CR_C4D1
```

I changed the group levels both ways, it always chooses C4D1 as the reference.
Am I missing anything? 

Thanks!
Tommy

**Comment by SimoneTiberi** [comment]
Hi Ming,
`distinct::log2_FC` computes the FC with the 1st level of the "group" column as numerator, and the 2nd as denominator.
In your case `levels(colData(sce)$group)` should be: `refractory_CR_C1D1 refractory_CR_C4D1`

You can redefine the order of the levels as:
`colData(sce)$group = relevel(colData(sce)$group, "refractory_CR_C4D1")`

Now `levels(colData(sce)$group)` will be: `refractory_CR_C4D1 refractory_CR_C1D1`
Then run `distinct::log2_FC` (no need to re-run `distinct_test`!).

Let me know if there are issues.
Simone

**Comment by crazyhottommy** [comment]
Thanks!

**Comment by crazyhottommy** [comment]
so I should specify the factor order in the design matrix and in the colData ?

**Comment by SimoneTiberi** [comment]
If you want, for coherency, you'd do both.
But really the design is not used in `distinct::log2_FC`, so the colData is sufficient.

**Comment by crazyhottommy** [comment]
got you! thanks.

**Comment by SimoneTiberi** [comment]
You're welcome.
Happy to help if you encounter further issues.
