### ISSUE TITLE
log2_FC error: Error in pb_2[, i] : subscript out of bounds

### ISSUE THREAD

**Issue by jeremymsimon** [SimoneTiberi/distinct#6]
I'm testing `distinct` on a new dataset, and ran the main `distinct_test` with seemingly no issues. However when I ran `log2_FC`, I get this error:

```
Error in pb_2[, i] : subscript out of bounds
```

After some testing, I determined that the issue is because two of my clusters are unique to one of my conditions:

```
Cluster	trt-Rep1	trt-Rep2	trt-Rep3	trt-Rep4	trt-Rep5	ctl-Rep1	ctl-Rep2	ctl-Rep3	ctl-Rep4	ctl-Rep5
38	18	0	1	45	1	0	0	0	0	0
39	15	1	0	38	0	0	0	0	0	0
```

and thus the dimensions of `pb_1` and `pb_2` are not equal. 

```
> dim(pb_1)
[1] 39469    43
> dim(pb_2)
[1] 39469    41
```

I can get around this error by doing something like:
`cluster_levels = intersect(colnames(pb_1),colnames(pb_2))` instead of `cluster_levels = colnames(pb_1)` on line 124 of this function.

Can you make this change, or add in a check/subset earlier on to make sure it doesn't fail here?

Thanks!

**Comment by SimoneTiberi** [comment]
Oh thanks for spotting this Jeremy!
Right, I must have missed it, I'll add it in the next release.

Thanks again,
Simone
