### ISSUE TITLE
Result data frame is NULL

### ISSUE THREAD

**Issue by StefTesta** [SimoneTiberi/distinct#7]
Hi Simone, 

Thank you for this great tool. 

I followed your vignette and tried to run a simple analysis comparing tumor versus normal cells from 3 samples. 

Everything when smoothly up to this point:
```

set.seed(61217)
res <-  distinct_test(x = sce_lms_endo, 
                    name_assays_expression = "logcounts",
                    name_cluster = "classification_2",
                    name_sample = "sample",
                    design = design,
                    column_to_test = 2,
                    min_non_zero_cells = 20,
                    n_cores = 4)

2 groups of samples provided
Covariates detected
Data loaded, starting differential testing
Differential testing completed, returning results
```
Then then when I tried to calculate the log2FC I then got this error: 
```

res = log2_FC(res = res,
               x = sce_lms_endo, 
               name_assays_expression = "cpm",
               name_group = "classification",
               name_cluster = "classification_2")

Error in log2_FC(res = res, x = sce_lms_endo, name_assays_expression = "cpm",  : 
  is.data.frame(res) is not TRUE
```
It seems like the "res" data.frame was not created when running distinct_test.

Could you provide some insight in why this might be happening?

Thank you, 
Stefano

**Comment by SimoneTiberi** [comment]
Hi @StefTesta, 
I am glad you appreciate our tool.

Did you modify `res` after running `distinct_test`?
`res` is not a data.frame, so either it was modified after `distinct_test` or there was an error in `distinct_test`, and res is empty.

Can you do 2 things:
- check `class(res)` and `head(res)`;
- write the full script you run with messages.

Thanks
